openapi: 3.0.1
info:
  title: VKBLRY* Challenges
  version: 0.0.1
servers:
- url: http://localhost:3000
paths:
  /api:
    get:
      tags:
      - server
      summary: Get list of all Challgenges.
      operationId: getAllChallenges
      responses:
        "200":
          description: returns all Challgenges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Challenge'
                x-content-type: application/json
      x-swagger-router-controller: Server
    post:
      tags:
      - server
      summary: Add a Challenge to the list.
      operationId: addChallenge
      requestBody:
        description: contains Challenge object that should be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Challenge'
        required: true
      responses:
        "201":
          description: Created
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: Server
  /:
    get:
      tags:
      - server
      summary: Get a user interface for VCBLRY*-trainer (index.html), which uses this API.
      operationId: servePublicFile_index
      responses:
        "200":
          description: returns index.html
          content:
            text/html:
              schema:
                type: string
        "404":
          description: not found
          content: {}
      x-swagger-router-controller: Server
  /{publicfilename}:
    get:
      tags:
      - server
      summary: Get files from public directory.
      operationId: servePublicFile
      parameters:
        - in: path
          name: publicfilename
          schema:
            type: string
          required: true
      responses:
        "200":
          description: returns public file
          content:
            text/html:
              schema:
                type: string
        "404":
          description: not found
          content: {}
      x-swagger-router-controller: Server
components:
  schemas:
    Challenge:
      type: object
      properties:
        id:
          type: string
        list:
          type: array
          items:
            $ref: '#/components/schemas/Word'
      example:
        id: Tiere / animals
        list:
        - A: Hund
          B: dog
        - A: Katze
          B: cat
    Word:
      type: object
      properties:
        A:
          type: string
        B:
          type: string
      example:
        A: Maus
        B: mouse
